bot:
  name: broker
  token: 5918374980:AAHLNor9QvhckZJB8OgglLOm-WYqNGTYd9Y

spring:
  application:
    name: bot
  kafka:
    bootstrap-servers: localhost:9092
    consumer.auto-offset-reset: earliest

chart:
  width: 640
  height: 480